compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
mixed_precision: bf16
num_processes: 4
num_machines: 1
gpu_ids: 0,1,2,3
machine_rank: 0
rdzv_backend: static
same_network: true
use_cpu: false
debug: false
