# aic/agents/comms_agent.py
"""
Communications & Postmortem Agent — auto-generates full incident documentation.

At episode end, generates:
  - Executive Summary (2 sentences, business language)
  - Engineering Summary (technical timeline)
  - Customer-Safe Summary (PR-safe version)
  - Postmortem Draft (full structured doc)
  - Remediation Checklist
  - Prevention Recommendations

Template-based — no LLM required. Rich variable substitution gives
realistic, scenario-specific output every time.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class TimelineEntry:
    step: int
    event: str
    agent: str
    impact: str


@dataclass
class PostmortemReport:
    """Full postmortem report for one episode."""
    generated_at: str
    scenario_name: str
    root_cause: str
    severity: str
    mttr_steps: int
    final_health: float
    sla_met: bool

    executive_summary: str
    engineering_summary: str
    customer_safe_summary: str

    timeline: list[TimelineEntry]
    contributing_factors: list[str]
    key_decisions: list[str]
    debate_highlights: list[str]

    remediation_checklist: list[str]
    prevention_recommendations: list[str]

    revenue_impact_usd: float
    users_protected: int
    slo_impact: str

    def to_markdown(self) -> str:
        """Render postmortem as a formatted markdown document."""
        sla_status = "✅ Met" if self.sla_met else "❌ Breached"
        health_pct = f"{self.final_health * 100:.1f}%"

        lines = [
            f"# 🚨 Incident Postmortem: {self.scenario_name}",
            f"> Generated by AIC Comms Agent at {self.generated_at}",
            "",
            "## 📋 Executive Summary",
            self.executive_summary,
            "",
            "## 👥 Customer Communication",
            self.customer_safe_summary,
            "",
            "## ⚙️ Engineering Summary",
            self.engineering_summary,
            "",
            "## 📊 Impact Metrics",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Severity | **{self.severity}** |",
            f"| MTTR | **{self.mttr_steps} steps** |",
            f"| SLA | {sla_status} |",
            f"| Final System Health | {health_pct} |",
            f"| Revenue Protected | **${self.revenue_impact_usd:,.0f}** |",
            f"| Users Protected | {self.users_protected:,} |",
            f"| SLO Impact | {self.slo_impact} |",
            "",
            "## 🔍 Root Cause",
            f"> {self.root_cause}",
            "",
            "## 📅 Incident Timeline",
        ]

        for t in self.timeline:
            lines.append(f"- **Step {t.step}** [{t.agent}]: {t.event} — *{t.impact}*")

        lines += [
            "",
            "## ⚠️ Contributing Factors",
        ]
        for cf in self.contributing_factors:
            lines.append(f"- {cf}")

        lines += [
            "",
            "## 🧠 Key Decisions (AIC Reasoning)",
        ]
        for kd in self.key_decisions:
            lines.append(f"- {kd}")

        if self.debate_highlights:
            lines += ["", "## 🗣️ Agent Debate Highlights"]
            for dh in self.debate_highlights:
                lines.append(f"> {dh}")

        lines += [
            "",
            "## ✅ Remediation Checklist",
        ]
        for item in self.remediation_checklist:
            lines.append(f"- [ ] {item}")

        lines += [
            "",
            "## 🛡️ Prevention Recommendations",
        ]
        for rec in self.prevention_recommendations:
            lines.append(f"- {rec}")

        lines += [
            "",
            "---",
            "*Auto-generated by AIC Comms Agent — Adaptive Incident Choreographer*",
        ]

        return "\n".join(lines)

    def to_dict(self) -> dict:
        return {
            "generated_at": self.generated_at,
            "scenario_name": self.scenario_name,
            "root_cause": self.root_cause,
            "severity": self.severity,
            "mttr_steps": self.mttr_steps,
            "final_health": self.final_health,
            "sla_met": self.sla_met,
            "executive_summary": self.executive_summary,
            "engineering_summary": self.engineering_summary,
            "customer_safe_summary": self.customer_safe_summary,
            "timeline": [{"step": t.step, "event": t.event, "agent": t.agent, "impact": t.impact} for t in self.timeline],
            "contributing_factors": self.contributing_factors,
            "key_decisions": self.key_decisions,
            "debate_highlights": self.debate_highlights,
            "remediation_checklist": self.remediation_checklist,
            "prevention_recommendations": self.prevention_recommendations,
            "revenue_impact_usd": self.revenue_impact_usd,
            "users_protected": self.users_protected,
            "slo_impact": self.slo_impact,
        }


# ── Scenario-specific templates ───────────────────────────────────────────

_ROOT_CAUSE_TEMPLATES: dict[str, str] = {
    "Cache Stampede": (
        "Redis cluster experienced a mass key eviction event, causing all cache entries "
        "to expire simultaneously. The resulting thundering herd drove the database connection "
        "pool to saturation, triggering cascading latency and queue backlog."
    ),
    "Canary Failure": (
        "A canary deployment with an undetected regression received 10% of production traffic. "
        "The faulty build caused error rate elevation for a subset of users; observability "
        "gaps delayed detection for multiple steps."
    ),
    "Regional Outage": (
        "An availability zone failure caused all services to degrade simultaneously. "
        "Network I/O monitoring was blinded, masking the true scope of impact during "
        "the initial response window."
    ),
    "Schema Migration Disaster": (
        "A database schema migration locked critical tables and introduced telemetry field "
        "renames that masked the severity. Replication lag compounded the DB latency spike, "
        "risking data divergence between primary and replica."
    ),
    "Credential Compromise": (
        "Leaked API credentials were exploited in a brute-force attack. The WAF throttled "
        "traffic in response, degrading throughput. SLA compliance monitoring was blinded "
        "during the active compromise window."
    ),
    "Queue Cascade": (
        "A consumer group rebalance storm caused the message queue to accumulate at an "
        "unsustainable rate. Backpressure propagated to p95 latency and error rate. "
        "Telemetry unit shifts masked the true queue depth during early response steps."
    ),
}

_REMEDIATION_BY_SCENARIO: dict[str, list[str]] = {
    "Cache Stampede": [
        "Implement cache stampede protection (lock-based or probabilistic early expiry)",
        "Add circuit breaker on DB connection pool to reject new connections above 90%",
        "Configure Redis key TTL jitter to prevent mass simultaneous eviction",
        "Set up CloudWatch alarm on conn_pool_pct > 80% with 60s response SLA",
        "Pre-warm cache on deployment; add cache-aside pattern with fallback throttling",
    ],
    "Canary Failure": [
        "Implement automatic canary rollback on error_rate > 2% sustained for 3 minutes",
        "Restore full observability coverage — remove error_rate blackout window",
        "Add p99 latency gate to canary promotion criteria",
        "Ensure canary traffic weight is < 5% for next 30 days",
        "File tracking ticket for observability gap remediation (P2)",
    ],
    "Regional Outage": [
        "Verify multi-AZ failover configuration and test quarterly",
        "Fix net_io_mbps monitoring blackout — restore full telemetry coverage",
        "Add health check endpoints per AZ with cross-region aggregation",
        "Review traffic routing policy for automatic failover trigger thresholds",
        "Conduct chaos engineering drill for AZ-loss scenario within 14 days",
    ],
    "Schema Migration Disaster": [
        "Mandate blue-green schema deployments — no in-place migrations on live tables",
        "Add pre-migration replication lag check (reject if lag > 50ms)",
        "Fix telemetry field rename — restore 'db_latency_ms' canonical naming",
        "Add migration dry-run in staging with full traffic replication for 24h",
        "Implement read replica promotion automation if replication lag > 200ms for 5 min",
    ],
    "Credential Compromise": [
        "Rotate all affected API credentials immediately",
        "Enable anomaly detection on auth_failure_rate with 1-minute alerting",
        "Restore sla_compliance_pct monitoring — patch the telemetry blackout",
        "Review WAF rate limiting rules — consider IP allowlisting for enterprise APIs",
        "Conduct credential audit across all services; implement secret scanning in CI",
    ],
    "Queue Cascade": [
        "Add consumer group lag alert: dead-letter queue after 10k unprocessed messages",
        "Fix queue_depth telemetry unit — restore native units (not ×0.001 scaling)",
        "Implement backpressure-aware rate limiter on queue producers",
        "Add auto-scaling trigger for consumer replicas on queue_depth > 500",
        "Schedule consumer group rebalance only during off-peak hours",
    ],
}

_PREVENTION_BY_SCENARIO: dict[str, list[str]] = {
    "Cache Stampede": [
        "Deploy Redis Sentinel or Cluster with consistent key distribution",
        "Add synthetic monitoring for cache hit rate; alert on < 85%",
        "Implement DB connection pool soft limits with graduated throttling",
    ],
    "Canary Failure": [
        "Gate all canary deployments behind error rate, latency, and saturation checks",
        "Establish 'shift-left' integration tests replicating production traffic patterns",
    ],
    "Regional Outage": [
        "Maintain active-active architecture across ≥ 3 availability zones",
        "Implement chaos engineering program testing AZ failure quarterly",
    ],
    "Schema Migration Disaster": [
        "Enforce schema-as-code reviews with automated compatibility checks",
        "Never run DDL migrations during peak traffic windows",
    ],
    "Credential Compromise": [
        "Implement zero-trust architecture with short-lived API credentials (TTL < 1h)",
        "Deploy ML-based auth anomaly detection integrated with automatic throttling",
    ],
    "Queue Cascade": [
        "Design queue consumers with graceful degradation and dead-letter routing",
        "Instrument queue producer for backpressure signals and auto-throttling",
    ],
}


class CommsAgent:
    """
    Generates structured incident communications at episode end.

    Input: episode trajectory (list of step dicts from run_episode).
    Output: PostmortemReport with all sections populated.
    """

    REVENUE_PER_STEP = 5000.0   # $ per healthy step (matches benchmark_suite)
    BASE_USERS = 50_000

    def generate_postmortem(
        self,
        scenario_name: str,
        episode_traces: list[dict],
        final_health: float,
        mttr_steps: int,
        root_cause_hypothesis: Optional[dict] = None,
        business_severity: str = "P2",
        debate_rounds: Optional[list[dict]] = None,
        total_revenue_saved: float = 0.0,
    ) -> PostmortemReport:
        """
        Generate a full postmortem report from episode data.

        Args:
            scenario_name: Name of the scenario (matches SCENARIO_REGISTRY).
            episode_traces: List of step dicts from trajectory.
            final_health: Final episode health score [0, 1].
            mttr_steps: Steps until first health > 0.5.
            root_cause_hypothesis: Bayesian root cause dict from analyst.
            business_severity: P1-P4 business severity level.
            debate_rounds: List of debate round dicts (optional).
            total_revenue_saved: Revenue protected during episode.
        """
        now = datetime.now(tz=__import__('datetime').timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        sla_met = final_health > 0.5

        # Root cause
        root_cause = _ROOT_CAUSE_TEMPLATES.get(
            scenario_name,
            f"Cascading failure originating in {scenario_name.lower()} service tier.",
        )
        if root_cause_hypothesis:
            confidence = root_cause_hypothesis.get("confidence", 0)
            analyst_name = root_cause_hypothesis.get("scenario_name", scenario_name)
            root_cause = (
                f"[AIC RCA confidence: {confidence:.0%}] {root_cause} "
                f"Root Cause Analyst identified '{analyst_name}' as primary hypothesis."
            )

        # Timeline from traces
        timeline = self._build_timeline(episode_traces, scenario_name)

        # Key decisions
        key_decisions = self._extract_key_decisions(episode_traces)

        # Debate highlights
        debate_highlights = self._extract_debate_highlights(debate_rounds or [])

        # Contributing factors
        contributing_factors = self._build_contributing_factors(episode_traces, scenario_name)

        # Summaries
        health_pct = int(final_health * 100)
        mttr_desc = f"{mttr_steps} steps" if mttr_steps < 20 else "not achieved within SLA window"
        sla_str = "successfully maintained SLA compliance" if sla_met else "experienced SLA breach"

        executive_summary = (
            f"On {now}, AIC autonomously detected and responded to a '{scenario_name}' incident "
            f"(severity {business_severity}), achieving {health_pct}% system health recovery "
            f"with MTTR of {mttr_desc}. "
            f"The autonomous command system {sla_str}, protecting an estimated "
            f"${total_revenue_saved:,.0f} in revenue."
        )

        engineering_summary = (
            f"Incident: {scenario_name} (severity {business_severity}). "
            f"Detection: Step 0 (immediate). "
            f"Root cause confirmed by Bayesian analyst at step {min(3, len(episode_traces))}. "
            f"First remediation action applied at step 1. "
            f"MTTR: {mttr_desc}. "
            f"Orchestrator executed {len(episode_traces)} decision cycles, "
            f"with {len(key_decisions)} high-impact decisions. "
            f"Recovery Verifier blocked {sum(1 for t in episode_traces if t.get('trace', {}).get('verifier_report', {}) and not t.get('trace', {}).get('verifier_report', {}).get('approved', True))} "
            f"unsafe actions. Final system health: {health_pct}%."
        )

        customer_safe_summary = (
            f"We experienced a service disruption on {now}. "
            f"Our automated incident response system detected the issue immediately "
            f"and began remediation. "
            + ("Service has been fully restored." if sla_met else
               f"Service was partially degraded; full restoration is in progress.")
            + " We apologize for any inconvenience and are implementing preventative "
            f"measures to avoid recurrence."
        )

        # SLO impact
        slo_impact = (
            "Minor SLO impact — within error budget" if final_health > 0.8 else
            "Moderate SLO breach — error budget partially consumed" if final_health > 0.5 else
            "Significant SLO breach — error budget exhausted"
        )

        users_protected = int(min(self.BASE_USERS, self.BASE_USERS * final_health))

        remediation_checklist = _REMEDIATION_BY_SCENARIO.get(
            scenario_name, ["Review incident logs", "Patch root cause", "Validate monitoring"]
        )
        prevention_recommendations = _PREVENTION_BY_SCENARIO.get(
            scenario_name, ["Implement additional monitoring", "Conduct postmortem review"]
        )

        return PostmortemReport(
            generated_at=now,
            scenario_name=scenario_name,
            root_cause=root_cause,
            severity=business_severity,
            mttr_steps=mttr_steps,
            final_health=final_health,
            sla_met=sla_met,
            executive_summary=executive_summary,
            engineering_summary=engineering_summary,
            customer_safe_summary=customer_safe_summary,
            timeline=timeline,
            contributing_factors=contributing_factors,
            key_decisions=key_decisions,
            debate_highlights=debate_highlights,
            remediation_checklist=remediation_checklist,
            prevention_recommendations=prevention_recommendations,
            revenue_impact_usd=total_revenue_saved,
            users_protected=users_protected,
            slo_impact=slo_impact,
        )

    def _build_timeline(self, traces: list[dict], scenario_name: str) -> list[TimelineEntry]:
        entries = [
            TimelineEntry(
                step=0,
                event=f"Incident detected: {scenario_name}",
                agent="AIC System",
                impact="Automated monitoring triggered incident response",
            )
        ]
        for step_data in traces[:10]:  # Summarise first 10 steps
            step = step_data.get("step", 0)
            trace = step_data.get("trace", {})
            if not trace:
                continue
            action = trace.get("action_taken", "")[:80]
            agent = trace.get("followed_agent", "Orchestrator")
            override = trace.get("override_applied", False)
            impact_note = "(override applied)" if override else "(trust-selected)"
            entries.append(TimelineEntry(
                step=step,
                event=action,
                agent=agent,
                impact=impact_note,
            ))
        return entries

    def _extract_key_decisions(self, traces: list[dict]) -> list[str]:
        decisions = []
        for step_data in traces:
            trace = step_data.get("trace", {})
            if not trace:
                continue
            if trace.get("override_applied"):
                reason = trace.get("override_reason", "trust threshold breach")
                decisions.append(f"Step {trace.get('step', '?')}: Override applied — {reason[:100]}")
            verifier = trace.get("verifier_report", {})
            if verifier and not verifier.get("approved", True):
                decisions.append(
                    f"Step {trace.get('step', '?')}: Safety Verifier blocked unsafe action "
                    f"(risk={verifier.get('risk_score', 0):.2f})"
                )
            if (trace.get("root_cause_hypothesis") or {}).get("confidence", 0) > 0.7:
                hyp = trace["root_cause_hypothesis"]
                decisions.append(
                    f"Step {trace.get('step', '?')}: Root cause confirmed — "
                    f"'{hyp['scenario_name']}' (confidence={hyp['confidence']:.0%})"
                )
        return decisions[:6] if decisions else ["Autonomous orchestrator managed all decisions within policy."]

    def _extract_debate_highlights(self, debate_rounds: list[dict]) -> list[str]:
        highlights = []
        for r in debate_rounds:
            for crit in r.get("criticisms", [])[:1]:
                highlights.append(crit.get("text", "")[:150])
            for veto in r.get("security_vetoes", [])[:1]:
                highlights.append(f"🔒 Security veto: {veto.get('reason', '')[:120]}")
            if r.get("debate_changed_selection"):
                highlights.append("⚠️ Debate altered final agent selection this step.")
        return highlights[:4]

    def _build_contributing_factors(self, traces: list[dict], scenario_name: str) -> list[str]:
        factors = [f"Primary fault: {scenario_name} incident pattern"]
        has_drift = any(
            t.get("trace", {}).get("schema_drift_detected") for t in traces
        )
        if has_drift:
            factors.append("Telemetry schema drift detected mid-incident, complicating diagnosis")
        has_override = any(
            t.get("trace", {}).get("override_applied") for t in traces
        )
        if has_override:
            factors.append("Adversarial recommendations required trust-based override")
        factors.append("Multi-metric cascading effect across service boundaries")
        factors.append("Progressive fault drift compounded initial fault vector")
        return factors
